server:
  port: 7878
spring:
  profiles:
    active: test
  application:
    name: k8s-connect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Sql@1234
   # url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/k8sDB?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/k8sDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
management:
  auditevents:
    enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    name: '@project.name@'
    version: '@project.version@'
    
