server:
  port: 7878
spring:
  application:
    name: k8s-connect
  datasource:
#    password: Sql@1234
#    url: jdbc:mysql://mysqldb/k8sDB  #points to k8s cluster
#    username: root
     url: jdbc:mysql://${DB_HOST:localhost}:3306/k8sDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
     username: ${DB_USERNAME:root}
     password: ${DB_PASSWORD:Sql@1234}
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

