server:
  port: 7878
spring:
  application:
    name: k8s-connect
  datasource:
    password: Sql@1234
    url: jdbc:mysql://192.168.99.100:33060/k8sDB  #points to docker images or container
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

