apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-traffic
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
  ingress: 
  - from:
    - podSelector:
        matchLabels:
           app: kubernetes-docker-java1
    ports:
    - protocol: TCP
      port: 3306
