apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-data-loader
data:
 init.sql: |
      CREATE DATABASE IF NOT EXISTS k8sDB;
      USE `k8sDB`;
      DROP TABLE IF EXISTS `sample`;

      CREATE TABLE `sample`(
        `id` BIGINT(20) NOT NULL,
        `name` VARCHAR(255) DEFAULT NULL,
        `gender` VARCHAR(255) DEFAULT NULL
      );

      INSERT INTO sample VALUES (1, 'chy-001', 'MALE');
      INSERT INTO sample VALUES (2, 'chy-002', 'MALE');
      INSERT INTO sample VALUES (3, 'chy-003', 'MALE');